name: pr build by comment

on:
    issue_comment:
        types: [created, edited]

jobs:
    workflow:
        name: PR Comment Pipeline
        if: github.event.issue.pull_request
            && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
            && contains(github.event.comment.body, '/build')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: refs/pull/${{ github.event.issue.number }}/merge
            - name: Run './build.cmd Compile'
              id: NukeBuild
              run: ./build.cmd Compile
              env:
                  GH_PACKAGES_USER: ${{ github.repository_owner }}
                  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SIRA_SERVER_CODE: ${{ secrets.SIRA_SERVER_CODE }}
            - uses: actions/upload-artifact@v3
              with:
                  name: ${{ steps.NukeBuild.outputs.filename }}
                  path: ${{ steps.NukeBuild.outputs.artifactpath }}